# Generated by Django 5.1.3 on 2024-12-14 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField()),
                ('verify_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], max_length=5)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.account')),
            ],
        ),
    ]
