# Generated by Django 5.1.3 on 2024-12-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_account_avatar_alter_account_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
