# Generated by Django 5.1.3 on 2024-12-21 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_verification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bnbinformation',
            name='count_viewed',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ReviewClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spam_status', models.BooleanField()),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.review')),
            ],
        ),
    ]
