# Generated by Django 5.1.3 on 2024-12-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_bnbinformation_count_viewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('checkin', 'Check-in'), ('checkout', 'Check-out'), ('refund', 'Refund'), ('secure', 'Secure'), ('other', 'Other')], default='other', max_length=9),
        ),
    ]
