# Generated by Django 5.1.3 on 2024-12-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_rule_rule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
